micronaut:
    application:
        name: dashboard
    router:
        static:
            resources:
                enabled: true
                mapping: /**
                paths: classpath:public
    server:
        port: 8080
    security:
        enabled: true
        interceptUrlMap:
            -
                pattern: /
                httpMethod: GET
                access:
                    - isAnonymous()
            -
                pattern: /index.html
                httpMethod: GET
                access:
                    - isAnonymous()
application:
    apikey: XXX
    username: john
